# Generated by Django 4.1 on 2023-11-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tipohabitacion_comentario_tipo_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='image',
            field=models.ImageField(default='', upload_to='rooms', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='lema',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
