# Generated by Django 4.1 on 2023-11-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tipohabitacion_descripcion_tipohabitacion_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipohabitacion',
            old_name='image',
            new_name='imagen',
        ),
    ]
